feat: integrated left content
patondev/speed_dating_human_ai pull request #2
Opened 2020-06-15 12:26 UTC by hardisp

This PR for integrated the left side with real data.

2020-06-15 14:41 UTC, npaton requested changes
LGTM, just a couple minor changes 👍

2020-06-15 14:41 UTC, npaton commented on server/main.js
> +  const socialStageDuration = 3500;
We should restore the original stage duration.

2020-06-15 14:41 UTC, npaton commented on client/game/Timer.jsx
> +    seconds = seconds < 10 ? "0" + seconds : seconds;
You can use padStart for this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2020-06-15 14:41 UTC, npaton commented on client/game/Timer.jsx
> +    seconds = parseInt(timer % 60, 10);
You can out initialisation on same line as declaration here.

```suggestion
    let minutes = parseInt(timer / 60, 10);
    let seconds = parseInt(timer % 60, 10);
```

2020-06-15 14:41 UTC, npaton commented on client/game/TaskStimulus.jsx
> +        </div>
Looks like all this code is repeated and can go into PersonCard.

2020-06-16 02:37 UTC, npaton requested changes

2020-06-16 02:37 UTC, npaton commented on client/game/Timer.jsx
> +    );
You're doing the same thing twice here.

2020-06-16 02:37 UTC, hubertusputu1 approved these changes

2020-06-16 03:01 UTC, npaton requested changes

2020-06-16 03:01 UTC, npaton commented on client/game/Timer.jsx
> +    seconds = seconds < 10 ? seconds : seconds;
These 2 lines aren't doing anything now...

2020-06-16 03:06 UTC, npaton approved these changes

2020-06-16 03:07 UTC, merged